CREATE TABLE USER_DETAIL (
  ID INT NOT NULL ,
  NAME VARCHAR(120) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL ,
  STATUS VARCHAR(1) NOT NULL ,
  PASSWORD VARCHAR(400) NOT NULL ,
  PRIMARY KEY (ID) ,
  CONSTRAINT UNIQUE_EMAIL_USER_DETAIL UNIQUE (EMAIL)
);


create TABLE PERMISSION (
  ID INT NOT NULL,
  DESCRIPTION VARCHAR(120) NOT NULL,
  PRIMARY KEY (ID)
);

create TABLE USER_DETAIL_PERMISSION (
  ID_USER_DETAIL int NOT NULL ,
  ID_PERMISSION int NOT NULL ,
  PRIMARY KEY (ID_USER_DETAIL ,ID_PERMISSION),
  FOREIGN KEY (ID_USER_DETAIL) REFERENCES USER_DETAIL(id),
  FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION(ID)
);

create sequence PERMISSION_SEQ start 1;
create sequence USER_DETAIL_SEQ start 1;

INSERT INTO PERMISSION VALUES (nextval('PERMISSION_SEQ'),'ROLE_SUPER'); --01
INSERT INTO PERMISSION VALUES (nextval('PERMISSION_SEQ'),'ROLE_SALESMAN'); --02


