INSERT INTO  USER_DETAIL VALUES (nextval('USER_DETAIL_SEQ') , 'Pedro', 'pv.ciria@gmail.com','A','$2y$12$BTIJbAoUCFWokkPMndR3gu934ijW.ToUexMJOgZ.F0A97IFm7PJLS') ;


INSERT INTO USER_DETAIL_PERMISSION VALUES(1,1);
INSERT INTO USER_DETAIL_PERMISSION VALUES (1,2);
